fix(st): silence warnings when compiling with USB and FWU flags
There is no real use case to compile a software dedicated to USB boot
(by enabling STM32MP_USB_PROGRAMMER=1) with PSA_FWU_SUPPORT=1.
But when compiling with both those flags there are compilation errors:
plat/st/common/bl2_io_storage.c: In function 'plat_fwu_set_images_source':
plat/st/common/bl2_io_storage.c:716:39: error: variable 'img_uuid'
 set but not used [-Werror=unused-but-set-variable]
  716 |         const uuid_t *img_type_uuid, *img_uuid;
      |                                       ^~~~~~~~
plat/st/common/bl2_io_storage.c: In function 'plat_set_image_source':
plat/st/common/bl2_io_storage.c:771:26: error: variable 'spec' set but
 not used [-Werror=unused-but-set-variable]
  771 |         io_block_spec_t *spec;
      |                          ^~~~

Add __maybe_unused to silence the warnings. While at it replace all
__unused with __maybe_unused and correct some checkpatch warnings.

Signed-off-by: Yann Gautier <yann.gautier@st.com>
Change-Id: Id08588b9c9710a041bf960e5dbdbe485c86d9d7d
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/tf-a/+/297333
Tested-by: Yann GAUTIER <yann.gautier@foss.st.com>
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
ACI: CIBUILD <MDG-smet-aci-builds@list.st.com>
Reviewed-by: Yann GAUTIER <yann.gautier@foss.st.com>
Domain-Review: Yann GAUTIER <yann.gautier@foss.st.com>